# A list of reviewers to be added to pull requests (GitHub user name)

# Must Reviewer
must_reviewers:
  - kod-source
  - nguyenanh848292

reviewers:
  -

# A number of reviewers added to the pull request
# Set 0 to add all the reviewers (default: 0)
number_of_reviewers: 2

# Set to true to add assignees to pull requests
add_assignees: true
