name: code check
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.11.0
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.0

      - name: Install black
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: code_check
        run: black --check .
        continue-on-error: true

      - name: show_diff
        run: black --diff .
