name: test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Install Need Tool
        run: |
          python -m pip install --upgrade pip
          pip install opencv-python
          pip install opencv-contrib-python
          pip install "ocrd-fork-pylsd == 0.0.3"

      - name: PyTest
        run: |
          python script/test_main.py
          python script/test_function.py
